"""empty message

Revision ID: 22aa01383439
Revises: 3cbce6e5aac0
Create Date: 2020-02-16 20:11:27.681884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22aa01383439'
down_revision = '3cbce6e5aac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('People')
    op.drop_constraint('Campsite_name_key', 'Campsite', type_='unique')
    op.drop_column('Campsite', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campsite', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('Campsite_name_key', 'Campsite', ['name'])
    op.create_table('People',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"People_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('catchphrase', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='People_pkey')
    )
    # ### end Alembic commands ###
