"""empty message

Revision ID: 4ea01f7c673a
Revises: 9af066c5666e
Create Date: 2020-02-16 21:54:10.933850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea01f7c673a'
down_revision = '9af066c5666e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campsite', sa.Column('cooking_grills', sa.Boolean(), nullable=True))
    op.add_column('Campsite', sa.Column('swimming', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Campsite', 'swimming')
    op.drop_column('Campsite', 'cooking_grills')
    # ### end Alembic commands ###
