"""empty message

Revision ID: 66c2c33f34a1
Revises: d1ab494f1c9c
Create Date: 2020-02-17 17:16:49.005968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c2c33f34a1'
down_revision = 'd1ab494f1c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campsite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campsite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('distance_from_city', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('closest_city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('costs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yurts_and_cabins', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bathrooms', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ada_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('campfires', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('showers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('wifi', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('trash_bins', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('picnic_area', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pets_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('potable_water', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rv_parks', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hiking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('camping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('biking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kayaking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('swimming', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cooking_grills', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hunting', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='campsite_pkey'),
    sa.UniqueConstraint('name', name='campsite_name_key')
    )
    # ### end Alembic commands ###
