"""empty message

Revision ID: 805b6d9abfe4
Revises: dabde14d9d52
Create Date: 2020-02-17 16:45:57.362579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805b6d9abfe4'
down_revision = 'dabde14d9d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Campsite', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Campsite', type_='unique')
    # ### end Alembic commands ###
