"""empty message

Revision ID: 9af066c5666e
Revises: b2966bf69a7f
Create Date: 2020-02-16 21:51:24.089553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af066c5666e'
down_revision = 'b2966bf69a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campsite', sa.Column('biking', sa.Boolean(), nullable=True))
    op.add_column('Campsite', sa.Column('camping', sa.Boolean(), nullable=True))
    op.add_column('Campsite', sa.Column('hiking', sa.Boolean(), nullable=True))
    op.add_column('Campsite', sa.Column('kayaking', sa.Boolean(), nullable=True))
    op.add_column('Campsite', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Campsite', 'website')
    op.drop_column('Campsite', 'kayaking')
    op.drop_column('Campsite', 'hiking')
    op.drop_column('Campsite', 'camping')
    op.drop_column('Campsite', 'biking')
    # ### end Alembic commands ###
