"""empty message

Revision ID: b2966bf69a7f
Revises: e70973bc3dfd
Create Date: 2020-02-16 21:36:44.569969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2966bf69a7f'
down_revision = 'e70973bc3dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campsite', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Campsite', 'website')
    # ### end Alembic commands ###
