"""empty message

Revision ID: dabde14d9d52
Revises: ff55ab0e0677
Create Date: 2020-02-16 22:42:50.982031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabde14d9d52'
down_revision = 'ff55ab0e0677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campsite', sa.Column('hunting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Campsite', 'hunting')
    # ### end Alembic commands ###
