"""empty message

Revision ID: e70973bc3dfd
Revises: fc31cd797470
Create Date: 2020-02-16 20:16:13.316074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70973bc3dfd'
down_revision = 'fc31cd797470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campsite', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Campsite', 'description')
    # ### end Alembic commands ###
