"""empty message

Revision ID: ff55ab0e0677
Revises: 4ea01f7c673a
Create Date: 2020-02-16 21:58:57.819578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff55ab0e0677'
down_revision = '4ea01f7c673a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campsite', sa.Column('hunting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Campsite', 'hunting')
    # ### end Alembic commands ###
